#pragma once
// This file was autogenerated. Do not edit. //
#include "input.h"

void bind_input(nb::module_ &m)
{
    // Enums
    nb::enum_<TestEnum>(m, "TestEnum", R"nbdoc(An enum with values that have docstrings.)nbdoc", nb::is_arithmetic())
        .value("CAR", TestEnum::CAR, R"nbdoc(A car.)nbdoc")
        .value("TRUCK", TestEnum::TRUCK, R"nbdoc(A truck.)nbdoc")
        .value("BIKE", TestEnum::BIKE);

    // Classes
    nb::class_<Test>(m, "Test", R"nbdoc(A primary class.

Demonstrates the full @nb tag surface for classes.)nbdoc", nb::intrusive_ptr<Test>([](Test* o, PyObject* po) noexcept { o->set_self_py(po); }), nb::dynamic_attr())
        .def(nb::init<>(), R"nbdoc(Default-construct.)nbdoc")
        .def(nb::init<int &>(), "a"_a, R"nbdoc(Construct from an int reference.

Args:
    a: the input)nbdoc")
        .def("nontrivial_params", &Test::nontrivial_params, "a"_a, "b"_a = nullptr, "c"_a = std::vector<int>(), R"nbdoc(Complex parameters.

Args:
    a: a
    b: b
    c: c)nbdoc")
        .def("overload", nb::overload_cast<double &>(&Test::overload), "a"_a, R"nbdoc(An overloaded function.

Args:
    a: First param)nbdoc")
        .def("overload", nb::overload_cast<int>(&Test::overload), "b"_a, R"nbdoc(An overloaded function.

Args:
    b: Alternate param)nbdoc")
        .def("__magic__", &Test::magic, R"nbdoc(A magic method.)nbdoc")
        .def_prop_ro_static("static_prop", &Test::static_prop, R"nbdoc(Static read-only property.)nbdoc");

    nb::class_<Test2, Test>(m, "Test2", R"nbdoc(A second class with multiple bases and a custom factory.)nbdoc", nb::is_final())
        .def(nb::new_(&Test2::make), "a"_a, R"nbdoc(Construct via factory.

Args:
    a: the value

Returns:
    constructed Test2)nbdoc")
        .def_prop_rw("name", &Test2::get_name, &Test2::set_name, R"nbdoc(Get the name.

Returns:
    the name)nbdoc")
        .def_prop_ro("prop", &Test2::get_prop, R"nbdoc(Get a read-only prop.)nbdoc")
        .def("__iter__", &Test2::iter, R"nbdoc(Iterate this object.

Returns:
    iterator)nbdoc", nb::keep_alive<0, 1>());

    // Functions
    m.def("freefn", &freefn, "a"_a, "b"_a, R"nbdoc(A free function.

Args:
    a: Hello
    b: Bye

Returns:
    result)nbdoc");

    m.def("free_return_simple", &free_return_simple, R"nbdoc(Custom Python docstring.)nbdoc");

};
